//USER TYPES
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const SET_PHOTO_URL = "SET_PHOTO_URL";

//CHAT ROOM TYPES
export const SET_CURRENT_CHAT_ROOM = "SET_CURRENT_CHAT_ROOM";
export const SET_PRIVATE_CHAT_ROOM = "SET_PRIVATE_CHAT_ROOM";
export const SET_URSER_POSTS = "SET_URSER_POSTS";
